### ISSUE TITLE
Controller Exception Handling

### ISSUE THREAD

**Issue by twinhooker** [naturalist/kelp#37]
Hello, I try to use Kelp to write some APIs. I use many libs that throw exceptions even on validation level and I would like to handle all of them in one place. As for naked Plack applications I use Plack::Middleware::Exceptions with my own additions.
But Kelp handles exceptions itself and stringifies them.
I curios if it possible for Kelp to rethrow exptions than some kind of Plack::Middleware::Exceptions will handle them.

**Comment by naturalist** [comment]
At the moment all exceptions are stringified, so they don't end up converted to JSON. It should be easy to add a patch that looks for a %ENV or internal variable and instructs Kelp to __not__ stringinfy. 
If you can wait a few days, I can add that patch myself. If you already have that patch for that, I'd accept a pull request.

**Comment by twinhooker** [comment]
Not to stringify exception is not enought. Because Kelp::Response::render_500 will not save exeption object. 
I have patch that checks if  $ENV{KELP_RETHROW_ON_ERROR} is enabled and throws same object right after logging error message. If it is ok I can send pull request.
I don't have a better solution right now but after creating my own exception middleware I will look forward it.

**Comment by naturalist** [comment]
Send a pull request. Thanks.
