### ISSUE TITLE
Default value for 'opts' can not be a reference. at /usr/local/share/perl/5.18.2/Kelp/Base.pm line 41.

### ISSUE THREAD

**Issue by mishin** [naturalist/kelp#47]
What I do wrong?
cat test.t 
    use Kelp::Base;

    attr source => 'dbi:mysql:users';
    attr user   => 'test';
    attr pass   => 'secret';
    attr opts   => { PrintError => 1, RaiseError => 1 };

perl test.t 
Default value for 'opts' can not be a reference. at /usr/local/share/perl/5.18.2/Kelp/Base.pm line 41.
	Kelp::Base::attr('main', 'opts', 'HASH(0x9458d8)') called at /usr/local/share/perl/5.18.2/Kelp/Base.pm line 26
	Kelp::Base::__ANON__('opts', 'HASH(0x9458d8)') called at test.t line 6

**Comment by twinhooker** [comment]
Hello,
attr can be ether scalar, undef or CODEref but not HASHREF or ARRAYREF
so you should do following:
```
attr opts => sub { { PrintError => 1, RaiseError => 1 } }
```

**Comment by mishin** [comment]
Thanks, grate!
