### ISSUE TITLE
Failed bridge response code

### ISSUE THREAD

**Issue by yakudzo** [naturalist/kelp#50]
As documentation says `401 Unauthorized` response used to tell that it lacks of valid authentication and MUST provide WWW-Authenticate header. This problem solved better by Plack::Middleware::Auth::\* module family. But when there is lack of valid rights to access data client should get `403 Forbidden` response instead. Thats actually what bridge should do. So I changed tests and response.

Docs from here:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by naturalist** [comment]
Thanks!
