### ISSUE TITLE
Proposal: Path::Tiny instead of File::Slurp

### ISSUE THREAD

**Issue by stro** [naturalist/kelp#57]
Hi Stefan,

File::Slurp is used in only one place in Kelp script. File::Slurp has some problems: it fails in 5.30 and current dev Perls, and also in older Perls on some systems like Haiku or Windows.

Path::Tiny has the necessary functionality and doesn't suffer from File::Slurp problems. Path::Tiny is very likely to be already installed as a prerequisite for some other popular modules like Carton, Dist::Zilla, or tidyall.

**Comment by naturalist** [comment]
Hi Sergiy! Sounds good. Would you be able to submit a pull request for this? 
If not, that's OK. I can make the change myself, however it will take some time.
