### ISSUE TITLE
Kelp::Less cannot encode JSON on its own

### ISSUE THREAD

**Issue by brtastic** [naturalist/kelp#65]
Hello, thank you for this piece of software.
In Kelp.pm pod, section `Quick development using Kelp::Less` an example is given that is supposed to encode JSON, however for me it doesn't. Instead it throws an exception that no JSON decoder is available.
After some digging it seems a line is missing in the example: `module 'JSON';` that will load JSON encoder module into the app. Can you confirm this? Is it a documentation problem or a code problem (or more precisely, should that line be required)?

**Comment by naturalist** [comment]
Yeah, the documentation is lacking. You must add a JSON module in order to use it. Thanks for noticing. Feel free to send a pull request with updated docs :)
